# Generated by Django 3.1.2 on 2020-10-13 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0005_auto_20201013_1104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('employment', models.TextField(blank=True)),
                ('reason_of_interest', models.CharField(choices=[('FAMP', 'Family Pet'), ('PCHI', 'Pet For Child'), ('WTCH', 'Watchdog'), ('COMP', 'Companion'), ('BRED', 'Breeding'), ('HUNT', 'Hunting Dog'), ('GURD', 'Guard Dog'), ('BARN', 'Barn Cat/Mouser'), ('PCOM', 'Pet Companion')], max_length=5)),
                ('own_or_rent', models.CharField(choices=[('OWN', 'Own'), ('RENT', 'Rent')], max_length=5)),
                ('additional_info', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_owner', to=settings.AUTH_USER_MODEL)),
                ('pet_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_of_interest', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
