# Generated by Django 3.1.2 on 2020-10-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petapplication',
            name='mark_as_read',
            field=models.BooleanField(default=False),
        ),
    ]
