# Generated by Django 3.1.2 on 2020-10-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_petapplication_mark_as_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petapplication',
            name='additional_info',
            field=models.TextField(null=True),
        ),
    ]
