# Generated by Django 3.1.2 on 2020-10-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='spay_neuter',
            new_name='spayed_or_neutered',
        ),
    ]
