# Generated by Django 3.1.2 on 2020-10-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20201014_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(blank=True, choices=[('TBA', 'Available'), ('NOA', 'Adopted')], default='TBA', max_length=3),
        ),
    ]
