# Generated by Django 3.1.2 on 2020-10-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20201015_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(blank=True, choices=[('TBA', 'To Be Adopted'), ('NOA', 'Now Officially Adopted')], default='TBA', max_length=3),
        ),
    ]
