# Generated by Django 3.1.2 on 2020-10-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20201019_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
