# Generated by Django 3.1.2 on 2020-10-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20201019_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(blank=True, default='static/default-profile.png', null=True, upload_to='images/'),
        ),
    ]
