# Generated by Django 3.1.2 on 2020-10-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20201008_0651'),
        ('tbauser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite', to='pets.Pet'),
        ),
    ]
